export const primary: string = [
  'flex',
  'justify-center',
  'text-white',
  'font-medium',
  'px-4 py-2.5',
  'relative',
  'rounded-lg',
  'text-center',
  'cursor-pointer',
  '-rotate-2',
  'transform-gpu',
  'max-h-12',
  'box-border',
  'bg-gradient-to-tr',
  'from-blue-500',
  'to-sky-500',
  'font-mono',
  'whitespace-nowrap',

  'hover:to-sky-600',
  'hover:shadow-[-4px_4px_5px_rgba(0,0,0,0.3)]',

  "after:content-['']",
  'after:absolute',
  'after:border',
  'after:border-black',
  'after:rounded-lg',
  'after:bottom-0.5',
  'after:left-0.5',
  'after:w-full',
  'after:h-full',

  'hover:after:bottom-px',
  'hover:after:left-px',
].join(' ');

export const secondary: string = [
  'flex',
  'justify-center',
  'text-black',
  'font-medium',
  'px-4 py-2.5',
  'relative',
  'rounded-lg',
  'text-center',
  'cursor-pointer',
  '-rotate-2',
  'transform-gpu',
  'max-h-12',
  'box-border',
  'bg-gradient-to-tr',
  'from-white',
  'to-slate-100',
  'font-mono',
  'whitespace-nowrap',
  
  'border',
  'border-dashed',
  'border-black',

  'hover:to-slate-200',
  'hover:shadow-[-4px_4px_5px_rgba(0,0,0,0.3)]',

  "after:content-['']",
  'after:absolute',
  'after:border',
  'after:border-black',
  'after:rounded-lg',
  'after:bottom-0.5',
  'after:left-0.5',
  'after:w-[101%]',
  'after:h-[101%]',

  'hover:after:bottom-0',
  'hover:after:left-0',
].join(' ');